Description: CD12352 - Infrastructure as Code Project - Udagram

Parameters:
    EnvironmentName:
        Description: This name will be prefixed to all the resources.
        Type: String
    AMItoUse:
      Description: AMI to use for our base image
      Type: String
    BucketName:
      Description: S3 bucket to use
      Type: String
      Default: thim-project


Resources:
  # s3 Role
  RoleForS3MAccess: 
        Type: "AWS::IAM::Role"
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                        Service:
                            - ec2.amazonaws.com
                      Action:
                        - sts:AssumeRole
            Path: "/"
  S3BucketsInstanceProfile:
      Type: AWS::IAM::InstanceProfile
      Properties:
          Path: "/"
          Roles:
              - Ref: RoleForS3MAccess
  # An IAM policy that allows EC2 to list objects in S3
  S3BucketsPolicy:
      Type: AWS::IAM::Policy
      Properties:
          PolicyName: S3BucketsPolicy
          PolicyDocument:
              Statement:
                  - Effect: Allow
                    Action:
                    - s3:*
                    Resource: "*"
          Roles:
              - Ref: RoleForS3MAccess 
  
  # Load Balancer security group
  LBSecGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
          GroupDescription: Allow http to our load balancer
          VpcId:
              Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
          SecurityGroupIngress: 
              - IpProtocol: tcp
                FromPort: 80
                ToPort: 80
                CidrIp: 0.0.0.0/0
          SecurityGroupEgress: 
              - IpProtocol: tcp
                FromPort: 80
                ToPort: 80
                CidrIp: 0.0.0.0/0
          Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName} LB Security Group

  #  app servers Security group
  WebServerSecGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
          GroupDescription: Allow http to our hosts and SSH from local only
          VpcId:
              Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
          SecurityGroupIngress: 
              - IpProtocol: tcp
                FromPort: 80
                ToPort: 80
                CidrIp: 0.0.0.0/0
              - IpProtocol: tcp
                FromPort: 22
                ToPort: 22
                CidrIp: 0.0.0.0/0
          SecurityGroupEgress: 
              - IpProtocol: tcp
                FromPort: 0
                ToPort: 65535
                CidrIp: 0.0.0.0/0
          Tags:
            - Key: Name
              Value: !Sub ${EnvironmentName} App Server SecurityGroup

  #Load Balancer
  WebAppLB:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
          Type: "application"
          Subnets:
              - Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"
              - Fn::ImportValue: !Sub "${EnvironmentName}-PUB2-SN"
          Scheme: "internet-facing"
          SecurityGroups:
              - Ref: LBSecGroup
          Tags:
          - Key: "Env"
            Value: !Ref EnvironmentName
          - Key: "Name"
            Value: !Sub "${EnvironmentName}-${AWS::StackName}-lb"

  # We include a portion of the LaunchTemplate resource so you can use the UserData.
  WebAppLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateName: !Sub "${EnvironmentName}-web-servers"
      LaunchTemplateData:
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            apt-get update -y
            sudo apt-get install nginx -y
            service nginx start
        ImageId: !Ref AMItoUse
        SecurityGroupIds:
          - !Ref WebServerSecGroup
        InstanceType: t2.micro
        BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          Ebs:
            VolumeSize: '10'
        IamInstanceProfile:
          Name: !Ref WebAppInstanceProfile

  #Auto Scaling Group
  WebAppGroup:
      DependsOn: Listener
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties:
          VPCZoneIdentifier:
              - Fn::ImportValue: !Sub "${EnvironmentName}-PRIV-NETS"
          LaunchConfigurationName:
              Ref: WebAppLaunchConfig
          MinSize: "4"
          MaxSize: "7"
          TargetGroupARNs:
              - Ref: WebAppTargetGroup
          Tags:
            - Key: "Env"
              Value: !Ref EnvironmentName
              PropagateAtLaunch: True
            - Key: "Name"
              Value: !Sub "${EnvironmentName}-${AWS::StackName}-asg"
              PropagateAtLaunch: True
  #S3 bucket
  S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub '${BucketName}-${AWS::Region}-${AWS::AccountId}'
        #AccessControl: PublicRead
        PublicAccessBlockConfiguration:
           BlockPublicAcls: false
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
  
  Listener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      LoadBalancerArn: !Ref WebAppLB
      Port: 80
      Protocol: "HTTP"
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref WebAppTargetGroup

  #Listener Rule 
  ALBListenerRule:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
          Actions:
              - Type: forward
                TargetGroupArn: !Ref "WebAppTargetGroup"
          Conditions:
              - Field: path-pattern
                Values: [/]
          ListenerArn: !Ref "Listener"
          Priority: 1

  # Target Group 
  WebAppTargetGroup:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
          HealthCheckIntervalSeconds: 10
          HealthCheckPath: /
          HealthCheckProtocol: HTTP
          HealthCheckTimeoutSeconds: 8
          HealthyThresholdCount: 2
          Port: 80
          Protocol: HTTP
          UnhealthyThresholdCount: 5
          VpcId:
              Fn::ImportValue:
                  Fn::Sub: "${EnvironmentName}-VPCID"

  # Launch configuration to spin up servers
  WebAppLaunchConfig:
      Type: AWS::AutoScaling::LaunchConfiguration
      Properties:
          UserData:
              Fn::Base64: !Sub |
                  #!/bin/bash
                  apt-get update -y
                  apt-get install unzip awscli -y
                  apt-get install apache2 -y
                  systemctl start apache2.service
                  cd /var/www/html
                  aws s3 cp s3://udagram-webapp/index.html .
          ImageId: !Ref AMItoUse
          IamInstanceProfile: !Ref S3BucketsInstanceProfile
          SecurityGroups:
              - Ref: WebServerSecGroup
          InstanceType: t3.medium
          BlockDeviceMappings:
              - DeviceName: "/dev/sdk"
                Ebs:
                    VolumeSize: "10"

  
  WebAppInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvironmentName}-web-servers"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: 'Allow'
          Principal:
            Service:
            - 'ec2.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      Policies:
        - PolicyName: s3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:PutObject'
              Resource:
                - !Sub "arn:aws:s3:::${S3Bucket}/*"

  WebAppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: '/'
      Roles:
      - !Ref WebAppInstanceRole


Outputs:
    WebAppLBDNSName:
        Description: DNS name or Public URL of the Load Balancer
        Value: !Join ["", ["http://", !GetAtt WebAppLB.DNSName]]
        Export:
            Name: !Sub ${EnvironmentName}-LB-DNSName